name: Build and Test

on: [push] # Trigger the workflow when changes are pushed to the repository

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout code # Step to check out your code repository
        uses: actions/checkout@v2

      - name: Set up Java # Step to set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Specify the Java version you need

      - name: Build and test # Step to build and test your Android project
        run: |
          ./gradlew build
        # Add more build and test commands if needed

      - name: Upload test results # Step to upload test results (if applicable)
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/outputs/apk/androidTest/debug/app-debug.apk
